### ISSUE TITLE
person.c 수정

### ISSUE THREAD

**Issue by Ha-jimin** [OSSteamproject28/teamproject_28#18]
scanf("%s",p[c].name);
person.c  51번째 줄에 c가 정의되어 있지 않다고 나옵니다!
여기 수정 부탁드릴게요!!

**Comment by jungwonchae** [comment]
네 수정했습니다!

**Comment by jungwonchae** [comment]
지금 VScode로 보는데 코드가 전체적으로 에러 뜨는 것 같아서 다시 수정해볼게요
